import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";

import SideNav from "./components/side-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <div className="flex h-screen w-screen flex-row bg-slate-900 p-8">
            <SideNav />
            <div className="w-1/3">{children}</div>
            <div className="w-1/3"></div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
