import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";

import SideNav from "../components/home/side-nav";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <SessionProvider>
          <div className="w-full overflow-x-hidden">
            <SideNav />
            <div className="flex h-full min-h-screen w-screen flex-row justify-center">
              <div className="w-1/3 py-8">{children}</div>
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
