import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";

import SideNav from "../components/home/side-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <SideNav />
          <div className="flex h-full min-h-screen w-full flex-row justify-center bg-slate-900">
            <div className="w-1/3 py-8">{children}</div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
